### ISSUE TITLE
Requisitos de proyecto

### ISSUE THREAD

**Issue by SlayerWx** [LucioRuixo/Arkanoid-RayLib-#11]
![67295408-71fe5380-f4bd-11e9-869a-d3b0778f52ad](https://user-images.githubusercontent.com/36495549/67296727-3e242d80-f4bf-11e9-99c4-25e115d9b8dc.png)
a mi entender y opinión personal, cosas como "Elements" y meter todo elemento sea de lo que sea ahi dentro es un poco vago con respecto de lo que te podres encontrar, estaría bueno tener "elements gameplay" y ahí dentro tener el jugador, la pelota, mientras tener "elements UI" y tener cosas como los botones y demás.

**Comment by LucioRuixo** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/54895404/67303494-edb1cd80-f4c8-11e9-8fd3-592bd3730d9d.png)

Resuelto. Hice como dijiste y creé los filtros "Gameplay" y "UI" dentro de Elements para guardar los archivos de ball, levels y paddle y buttons, respectivamente.
