### ISSUE TITLE
Borde superior de los bloques a romper

### ISSUE THREAD

**Issue by SlayerWx** [LucioRuixo/Arkanoid-RayLib-#4]
![Screenshot_4](https://user-images.githubusercontent.com/36495549/67291653-3dd46400-f4b8-11e9-93b8-ad4a2e9e7bf9.png)
El usuario siempre busca la comodidad, por lo tanto intentara abrirse una abertura lo antes posible hacia arriba y golpear de forma sucesiva los bloques desde arriba con rebotes, en tu juego si un usuario logra darle al bloque desde arriba, la pelota **sigue de largo** y en realidad debería volver a rebotar.

**Comment by LucioRuixo** [comment]
En principio sí, podría desarrollar las colisiones para que la pelota rebote desde todos los lados de los bloques. Sin embargo, ya hay una colisión mínima (desde abajo) y prefiero dejarlo así para centrarme en otros errores.
