### ISSUE TITLE
choques que no rebotan y crean una sucesión

### ISSUE THREAD

**Issue by SlayerWx** [LucioRuixo/Arkanoid-RayLib-#5]
![Screenshot_5](https://user-images.githubusercontent.com/36495549/67291868-8db32b00-f4b8-11e9-95c7-acc3f5672796.png)
hay veces que la pelota cuando rebota contra un bloque y comienza a bajar, si toca la punta de los siguientes no le afecta la colisión y el bloque desaparece, yo creo que a esto debería colisionar la pelota y hacer su respectivo **cambio de trayectoria**.

**Comment by LucioRuixo** [comment]
Lo mismo que comenté en el error #4 .
