### ISSUE TITLE
al terminar la partida no se puede re-jugar

### ISSUE THREAD

**Issue by SlayerWx** [LucioRuixo/Arkanoid-RayLib-#6]
![Screenshot_6](https://user-images.githubusercontent.com/36495549/67292093-e71b5a00-f4b8-11e9-8857-a9832b433169.png)
Ganes o pierdas, **indiferentemente de cual sea el resultado de la partida**, cuando le doy a return y vuelvo al menú principal, al darle a play nuevamente **me vuelve a aparecer** el mensaje de "you win"/"you lose"

**Comment by LucioRuixo** [comment]
Resuelto. Me estaba olvidando de reiniciar los valores de los elementos del juego al terminar una partida. Ahora, cuando chequea que el jugador gana o pierde llama a las Initialize() de los ball, paddle y levels y es posible volver empezar una partida.
