### ISSUE TITLE
Falta de informacion

### ISSUE THREAD

**Issue by SlayerWx** [LucioRuixo/Arkanoid-RayLib-#7]
![Screenshot_7](https://user-images.githubusercontent.com/36495549/67292349-46796a00-f4b9-11e9-8a64-905bdbd15234.png)
a la hora de leer las instrucciones, **en ningún momento** se dice que la pelota es disparada/liberada con la tecla del espacio, cosa que aunque es medio obvia se debe poner para que el jugador no piense que se puede disparar con otra, tampoco aparece la Tecla P en la información de teclas para usar.

**Comment by LucioRuixo** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/54895404/67302561-6d3e9d00-f4c7-11e9-8348-290f77de0705.png)

![Screenshot_2](https://user-images.githubusercontent.com/54895404/67302567-6f086080-f4c7-11e9-8961-4f214a46ece0.png)

Resuelto. Añadí texto en el menú principal explicando todos los controles. De paso lo pasé a inglés porque era lo único del juego que estaba en español xD.
