### ISSUE TITLE
multiplicación innecesaria

### ISSUE THREAD

**Issue by SlayerWx** [LucioRuixo/Arkanoid-RayLib-#9]
![Screenshot_2](https://user-images.githubusercontent.com/36495549/67296260-9a3a8200-f4be-11e9-89ea-117ae177cf78.png)
no es necesario tener ese  "1 *" ya que quedara siempre el numero de la variable

**Comment by LucioRuixo** [comment]
Resuelto. No se por qué estaba ese 1 pero ya lo borré.
